// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmqNk84W0ihYBJBHYfPHfckBMYoRJ8Vic',
    appId: '1:507572063220:web:4292be01c0679d4d3dc7a1',
    messagingSenderId: '507572063220',
    projectId: 'fe-sabel-allah',
    authDomain: 'fe-sabel-allah.firebaseapp.com',
    storageBucket: 'fe-sabel-allah.firebasestorage.app',
    measurementId: 'G-KX54K3W66E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDehwTYCRJ32B5t4pWcduSEr8PQ_m0uSdk',
    appId: '1:507572063220:android:98091403b14a29e83dc7a1',
    messagingSenderId: '507572063220',
    projectId: 'fe-sabel-allah',
    storageBucket: 'fe-sabel-allah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcCUJQEUDdJUeIecD9axUyvPs2Jwe87Lg',
    appId: '1:507572063220:ios:08036c2ae3b6b94c3dc7a1',
    messagingSenderId: '507572063220',
    projectId: 'fe-sabel-allah',
    storageBucket: 'fe-sabel-allah.firebasestorage.app',
    iosBundleId: 'com.example.feSabelAllah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcCUJQEUDdJUeIecD9axUyvPs2Jwe87Lg',
    appId: '1:507572063220:ios:08036c2ae3b6b94c3dc7a1',
    messagingSenderId: '507572063220',
    projectId: 'fe-sabel-allah',
    storageBucket: 'fe-sabel-allah.firebasestorage.app',
    iosBundleId: 'com.example.feSabelAllah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmqNk84W0ihYBJBHYfPHfckBMYoRJ8Vic',
    appId: '1:507572063220:web:342b67bcd3d8fb283dc7a1',
    messagingSenderId: '507572063220',
    projectId: 'fe-sabel-allah',
    authDomain: 'fe-sabel-allah.firebaseapp.com',
    storageBucket: 'fe-sabel-allah.firebasestorage.app',
    measurementId: 'G-2TY0R4W0CX',
  );
}
